# -*- coding: utf-8 -*-
"""1.Pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNdY-D95ShFmFRsMdtLGHBCiDmZABVJ3
"""

import pandas as pd    #Frist import pandas as pd here pd is a alias

df = pd.read_csv("Titanic.csv")   # pd.read_csv() used to read data from a CSV (Comma Separated Values) file

df.head()   #This function extract first five values from data frame

df.tail() #This function extract last five values

df.columns #It gives the information about columns

df.describe() #It used to generate descriptive statistics of numeric columns

df.dtypes  #It gives the data dtype of columns

df['Age']  #It is used to select single column

df[['Name','Age']] #It is use to select more than one columns

df.dtypes == 'object' # In pandas string is treat as object , so you can see it return True where data type is object(string)

df.dtypes[df.dtypes == 'object'].index  #It return all object(string) columns

df[df.dtypes[df.dtypes == 'object'].index].describe()  #It is used to generate descriptive statistics of columns with data type object(string)

